package com.example.signuploginrealtime;

import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

public class studreg extends AppCompatActivity {

    private EditText usernameEditText, emailEditText, passwordEditText ;
    private Button submitButton;
    private FirebaseAuth mAuth;
    private DatabaseReference databaseReference;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_studreg);

        usernameEditText = findViewById(R.id.t1);
        emailEditText = findViewById(R.id.t2);
        passwordEditText = findViewById(R.id.t3);

        submitButton = findViewById(R.id.bt);

        mAuth = FirebaseAuth.getInstance();
        databaseReference = FirebaseDatabase.getInstance().getReference().child("users");

        submitButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                final String username = usernameEditText.getText().toString();
                final String email = emailEditText.getText().toString();
                final String password = passwordEditText.getText().toString();


                // Check if any field is empty
                if (username.isEmpty() || email.isEmpty() || password.isEmpty())  {
                    Toast.makeText(studreg.this, "Please fill all fields", Toast.LENGTH_SHORT).show();
                } else {
                    // Create user with email and password using Firebase Authentication
                    mAuth.createUserWithEmailAndPassword(email, password)
                            .addOnCompleteListener(studreg.this, new OnCompleteListener<AuthResult>() {
                                @Override
                                public void onComplete(@NonNull Task<AuthResult> task) {
                                    if (task.isSuccessful() && task.getResult() != null) {
                                        // Sign in success, update UI with the signed-in user's information
                                        FirebaseUser user = mAuth.getCurrentUser();
                                        if (user != null) {
                                            // Get the unique user ID generated by Firebase Authentication
                                            String userId = user.getUid();

                                            // Create a new user object using helper class
                                            helper newUser = new helper( username, email, password);

                                            // Push the user object to Firebase Database under "users" table with the unique user ID
                                            databaseReference.child(userId).setValue(newUser, new DatabaseReference.CompletionListener() {
                                                @Override
                                                public void onComplete(@NonNull DatabaseError error, @NonNull DatabaseReference ref) {
                                                    if (error == null) {
                                                        Toast.makeText(studreg.this, "User added to database", Toast.LENGTH_SHORT).show();
                                                        // Clear EditText fields after successful submission
                                                        usernameEditText.setText("");
                                                        emailEditText.setText("");
                                                        passwordEditText.setText("");

                                                    } else {
                                                        Toast.makeText(studreg.this, "Error: " + error.getMessage(), Toast.LENGTH_SHORT).show();
                                                    }
                                                }
                                            });
                                        }
                                    } else {
                                        // If sign in fails, display a message to the user.
                                        Toast.makeText(studreg.this, "Authentication failed: " + task.getException(), Toast.LENGTH_SHORT).show();
                                    }
                                }
                            });
                }
            }
        });
    }
}
